version: '2'

services:
  db:
    image: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bottle
      POSTGRES_DB: bottle
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data