version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run container:start

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bottle
      POSTGRES_DB: bottle
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data